# Generated by Django 5.1.2 on 2024-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('nome_completo', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('data_acesso', models.DateField()),
                ('hora_acesso', models.TimeField()),
                ('visitante', models.CharField(max_length=50)),
            ],
        ),
    ]
