# Generated by Django 5.1.2 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='curso',
            field=models.CharField(default='Indefinido', max_length=20),
            preserve_default=False,
        ),
    ]
