# Generated by Django 5.1.2 on 2025-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loginrecord_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='dia_da_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
